class bcolors:
    PURPLE = '\033[95m'
    MAGENTA = '\033[35m'
    CYAN = '\033[96m'
    DARKCYAN = '\033[36m'
    BLUE = '\033[94m'
    DARKBLUE = '\033[34m'
    GREEN = '\033[92m'
    DARKGREEN = '\033[32m'
    YELLOW = '\033[93m'
    ORANGE = '\033[33m'
    RED = '\033[91m'
    DARKRED = '\033[31m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    END = '\033[0m'

    def disable(self):
        self.PURPLE = ''
        self.MAGENTA = ''
        self.CYAN = ''
        self.DARKCYAN = ''
        self.BLUE = ''
        self.DARKBLUE = ''
        self.GREEN = ''
        self.DARKGREEN = ''
        self.YELLOW = ''
        self.ORANGE = ''
        self.RED = ''
        self.DARKRED = ''
        self.BOLD = ''
        self.UNDERLINE = ''
        self.END = ''